project:
  type: book

book:
  title: "Data Journalism with R and the Tidyverse"
  subtitle: "Spring 2024, Jour 472/772, Philip Merrill College of Journalism"
  author: "By Sean Mussenden, Rob Wells and Derek Willis Original authors: Matt Waite & Sarah Cohen"
  date: "12/19/2023"
  chapters:
     - index.qmd
     - start-story.qmd
     - start-math.qmd
     - census_data.qmd
     - xl-intro.qmd
     - xl-refresher.qmd
     - xl-filter-sort.qmd
     - xl-formulas.qmd
     - xl-pivot.qmd
     - xl-sheets_cleaning.qmd
     - r-start.qmd
     - r-load-analyze-visualize.qmd
     - github.qmd
     - r_aggregates_filters.qmd
     - r-mutating.qmd
     - r_visualizing_reporting.qmd
     - r-join-bind.qmd
     - r-data-cleaning.qmd
     - r-geographic-basics.qmd
     - r-geographic-analysis.qmd
     - r-tidycensus-api.qmd
     - r-scraping.qmd
     - r-publication.qmd
     - appendix-math.qmd

  #  - aggregates.qmd
  #  - mutating.qmd
  #  - workingwithdates.qmd
  #  - filters.qmd
  #  - datacleaning-part-i.qmd
  #  - datacleaning-part-ii.qmd
  #  - open-refine.qmd
  #  - pdfs.qmd
  #  - merging.qmd

format:
  html:
    theme: simplex
  #pdf:
  #  documentclass: scrreprt
 # epub:
 #    cover-image: cover.png

editor: visual

execute:
  cache: false